spring:
  application:
    name: CAR-RENTAL-SERVICE

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql/travelBooking?createDatabaseIfNotExist=true
    username: root
    password: JattaA@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

server:
  port: 1013

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://serviceregistry:1000/eureka
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      rentalInfoBreaker:
        register-health-indicator: true
        wait-duration-in-open-state: 2s
        max-wait-duration-in-half-open-state: 2s
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-size: 10
        sliding-window-type: count_based
        permitted-number-of-calls-in-half-open-state: 3

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"