spring:
  application:
    name: TRAVEL-BOOKING-SYSTEM-SERVICE-REGISTRY

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false

server:
  port: 1000
